# List


We have learned a variable has types. Simple type include
* None
* boolean
* integer
* float
* string

Now we learn another type: a list. It is not *simple* in the sense that a list is composed by simple types: A list is a collection of things in particular order.

With a list:
* you can put things into a list
* you can remove from a list
* you can slice a list to get a portion of it etc.



## Create new/empty list

List is denoted by `[ ... ]`.

In [4]:
names = []
len(names) == 0

True

In [6]:
names = ['qiqi', 'yangyang', 'mom', 'dad']
names


['qiqi', 'yangyang', 'mom', 'dad']

## Read any element in a list

Each element in a list has a position index (hidden), starting with 0.

In [2]:
print(names[0])

qiqi


In [3]:
print(names[3])

dad


In [4]:
print(names[4])

IndexError: list index out of range

## Read last element in a list

In [5]:
names[-1]

'dad'

In [8]:
names[-2]

'mom'

In [14]:
names[2:3]

['mom']

## Change, add, remove element from a list

In [6]:
names[0] = 'rachel.wang'
names

['rachel.wang', 'yangyang', 'mom', 'dad']

In [7]:
# add to the last
names.append('jingo')
names

['rachel.wang', 'yangyang', 'mom', 'dad', 'jingo']

In [8]:
# remove by value
names.remove('jingo')
names

['rachel.wang', 'yangyang', 'mom', 'dad']

In [15]:
names.insert(2, 'jingo')
names

['qiqi', 'yangyang', 'jingo', 'mom', 'dad']

In [18]:
names

['yangyang', 'jingo', 'mom', 'dad']

In [19]:
del names[3]
names

['yangyang', 'jingo', 'mom']

In [20]:
# remove last element from the list
ele = names.pop(2)
print("removed element is: ", ele)
names

removed element is:  mom


['yangyang', 'jingo']

In [12]:
# remove any element from list
ele = names.pop(0)
names

['yangyang', 'mom']

## Find the length of the list


In [13]:
len(names)

2

## Loop through a list

Often, we want to iterate or loop through **each element** in the list and do something about it. For example:
* find out min value
* find out max value
* calculate the sum
* calculate the average

Anway - to loop through element in a list, we use, ... **for** loop as shown below

In [22]:
for wang_family_member in names:
    print(wang_family_member)

print("That is all we have")

yangyang
jingo
That is all we have



## What does for loop really do?

Above code essentially are translated into the following sequential code:
```python
wang_family_member = "yangyang"
print(wang_family_member)
wang_family_member = "mom"
print(wang_family_member)
print("That is all we have")
```

The point is, it doesn't matter how many elements in the list, for loop will iterate each and every one of them with just these two lines.

`for` and `in` are reserved word.



## Code block and identions

Now we talk about the basic of for loop, it is a good time to know aobut **code block** and idention rules: python pays great attention to how you indent your code. If you miss-indent, it will complain. Even worse, it doesn't do what you intended. For example:

```python
for wang_family_member in names:
    print(wang_family_member)
    print("That is all we have")
```

Another example, tell me what will happen here?

```python
message = "hello world"
    print(message)
```



In [23]:
for wang_family_member in names:
    print(wang_family_member)
    print("That is all we have")

yangyang
That is all we have
jingo
That is all we have


In [25]:
message = "hello world"
print(message)

hello world


## The colon after the for

Also, pay attention to the colon after the `for wang_family_member in names:`. This colon tells for loop that the next line will be the start of the loop.


## Quick Exercises 1

* Think of a list of animals you like, put them in a list, and print them out one by one.
* Add a line at the very end, print out a line to tell which one is your favorite.


In [22]:
fav_animals = ['tigers', 'horses', 'Dogs', 'peacocks', 'dolphins', 'leopards', 'foxes']
fav_found = False
for my_favorite in fav_animals:
    if my_favorite == 'Eagles':
        fav_found = True
        print(my_favorite, "are my favorite animal")

if fav_found == False:
    print("This list does not have my favorite animals.")
        
        

This list does not have my favorite animals.


## range() function

often, we want to do certain things in fixed number times. For example, you want to shout out "I love you" five times, exact. So python provides a easy way of doing this: that generate a numerical list:

In [13]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [9]:
# to loop 5 times exact:
for i in range(1,6):
    print(i)

1
2
3
4
5


In [13]:
# generate a list a even number between up to 10
even_numbers = list(range(2,11,2))
print(even_numbers)

[2, 4, 6, 8, 10]


In [14]:
# calculate square numbers up to 20
squares = []
for i in range(21):
    squares.append(i**2)

print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


## Quick exercises 2


#1 Generate a list of numbers from 1 to one million

#2 Generate a list of cube numbers for 1 to 10 (a cube number is a number raised to the power of 3)



## Working with part of the list

You don't have to work with the whole list: a list can be *sliced*.


In [19]:
import numpy as np
np.random.seed(0)
numbers = np.random.randint(0, 100, 50)
print(numbers)


[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88 81 37 25 77
 72  9 20 80 69 79 47 64 82 99 88 49 29 19 19 14 39 32 65  9 57 32 31 74
 23 35]


In [20]:
# first 3 elements
numbers[0:3]


array([44, 47, 64])

In [23]:
# last 4 elements
numbers[-4:]

array([31, 74, 23, 35])

In [24]:
# middle from index 4 to end
numbers[4:]

array([67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39, 87, 46, 88, 81,
       37, 25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99, 88, 49, 29, 19,
       19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23, 35])

## Copy a list

you can create a copy of the list by:


In [26]:
original = [2.3, 3.5, 8.9]
new_list = original[:]
print("original = ", original)
print("new_list = ", new_list)

original =  [2.3, 3.5, 8.9]
new_list =  [2.3, 3.5, 8.9]


In [27]:
original.append(10)
print("original = ", original)
print("new_list = ", new_list)

original =  [2.3, 3.5, 8.9, 10]
new_list =  [2.3, 3.5, 8.9]
